# Generated by Django 6.0 on 2025-12-27 12:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Tithe', 'Tithe'), ('Utilities', 'Utilities'), ('Shopping', 'Shopping'), ('Spotify', 'Spotify'), ('Healthcare', 'Healthcare'), ('Groceries', 'Groceries'), ('Other Expenses', 'Other Expenses'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Gift', 'Gift'), ('Spotify-IN', 'Spotify-IN'), ('Other Income', 'Other Income')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['type', 'date'], name='dashboard_t_type_ccfcc8_idx'), models.Index(fields=['category', 'date'], name='dashboard_t_categor_53ac67_idx')],
            },
        ),
    ]
