# Generated by Django 6.0 on 2026-01-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='dashboard_t_type_ccfcc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='dashboard_t_categor_53ac67_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
